version: "3.9"
services:
  database:
    container_name: postgres
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_password"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
